version: '2'
services:
  db:
    image: postgres

  web:
    build: .
    command: ["/finka/docker-entrypoint.sh", "5432"]
    volumes:
      - .:/finka
      - bbox:/box
    ports:
      - "3000:3000"
    depends_on:
      - db
      - box
      - redis

  box:
    image: busybox
    volumes:
      - bbox:/box

  redis:
    image: redis

volumes:
  bbox: