version: '2'
services:
  db:
    image: postgres

  web:
    build: .
    volumes:
      - .:/finka
      - bbox:/box
    ports:
      - "3000:3000"
    depends_on:
      - db
      - box
      - redis

  box:
    image: busybox
    volumes:
      - bbox:/box

  redis:
    image: 'redis'
    command: redis-server --requirepass yourpassword
    ports:
      - '6379:6379'

volumes:
  bbox: